//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Infraestrutura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int codPessoa { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string sexo { get; set; }
        public Nullable<bool> ativo { get; set; }
    }
}
