//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Infraestrutura
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public int codUsuario { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string perfil { get; set; }
        public Nullable<bool> ativo { get; set; }
    }
}
